services:
  - type: web
    name: social-media-api
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn social_media_api.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: social-media-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHON_VERSION
        value: 3.11.0

databases:
  - name: social-media-db
    plan: free
